[toolchain]
solana_version = "2.1.12"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smartcontracts = "8AUqDmrhdj55j6a2QcwYnm2j8oxUYgefZAH5sShqbx2H"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
